// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hint describing what kind of canvas mutation occurred.
 *
 * Sent alongside canvas state syncs so that SSE subscribers can react
 * to specific changes without diffing the full snapshot.
 */
export type CanvasEventHint = { "kind": "tab_opened", 
/**
 * The ID of the opened tab.
 */
tab_id: string, 
/**
 * The user-friendly label of the opened tab.
 */
label: string, } | { "kind": "tab_switched", 
/**
 * The ID of the tab that is now active.
 */
tab_id: string, 
/**
 * The user-friendly label of the switched-to tab.
 */
label: string, } | { "kind": "tab_closed", 
/**
 * The ID of the closed tab.
 */
tab_id: string, 
/**
 * The user-friendly label of the closed tab.
 */
label: string, } | { "kind": "layout_changed", 
/**
 * The context/tab ID where the layout changed.
 */
context_id: string, 
/**
 * The new layout identifier.
 */
layout_id: string, } | { "kind": "state_sync" };
