// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceType } from "./SourceType";

/**
 * Provenance tracking for drift detection.
 *
 * This enables runi's killer feature: knowing when upstream specs change.
 *
 * # Research Context
 * - 75% of APIs don't match their specs (Salt Security 2024)
 * - No existing tool tracks spec source URL for re-fetch
 * - SHA-256 hash enables cheap "did spec change?" detection
 */
export type CollectionSource = { 
/**
 * How this collection was created.
 */
source_type: SourceType, 
/**
 * Original URL for re-fetching (drift detection).
 */
url: string | null, 
/**
 * SHA-256 hash of normalized spec: "sha256:abc123...".
 */
hash: string | null, 
/**
 * Spec version from info.version field.
 */
spec_version: string | null, 
/**
 * When spec was fetched: "2026-01-31T10:30:00Z".
 */
fetched_at: string, 
/**
 * Git commit SHA if spec came from a repo.
 */
source_commit: string | null, 
/**
 * Path to the git repo root for tracked specs.
 */
repo_root?: string | null, 
/**
 * Relative path to the `OpenAPI` spec within the repo.
 */
spec_path?: string | null, 
/**
 * Git ref (branch/tag/commit) being tracked.
 */
ref_name?: string | null, };
