// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriftActionType } from "./DriftActionType";

/**
 * Result of executing a drift resolution action.
 */
export type DriftActionResult = { 
/**
 * Whether the action was applied successfully.
 */
success: boolean, 
/**
 * The action that was executed.
 */
actionType: DriftActionType, 
/**
 * Human-readable message describing the outcome.
 */
message: string, };
