// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriftActionType } from "./DriftActionType";

/**
 * A suggested action to resolve a detected drift.
 */
export type DriftSuggestedAction = { 
/**
 * The type of resolution action.
 */
actionType: DriftActionType, 
/**
 * Human-readable label for the action button.
 */
label: string, 
/**
 * Description of what this action will do.
 */
description: string, };
