// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestTiming } from './RequestTiming';

/**
 * Response from an HTTP request.
 */
export type HttpResponse = {
  /**
   * HTTP status code.
   */
  status: number;
  /**
   * HTTP status text (e.g., "OK", "Not Found").
   */
  status_text: string;
  /**
   * Response headers as key-value pairs.
   */
  headers: Record<string, string>;
  /**
   * Response body as a string.
   */
  body: string;
  /**
   * Timing information for the request.
   */
  timing: RequestTiming;
};
