// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of an import operation — either success or a name conflict.
 *
 * When the parsed spec's title matches an existing collection, a `Conflict`
 * is returned instead of silently creating a versioned duplicate.
 */
export type ImportCollectionResult = { "status": "success", 
/**
 * The newly created collection.
 *
 * Note: `Collection` does not derive `TS` (due to `#[serde(flatten)]`
 * with `serde_yaml_ng::Value`). The frontend has a manually-maintained
 * `Collection` type in `src/types/collection.ts`.
 */
collection: Record<string, unknown>, } | { "status": "conflict", 
/**
 * ID of the existing collection.
 */
existing_id: string, 
/**
 * Display name of the existing collection.
 */
existing_name: string, 
/**
 * Spec version of the existing collection (e.g., "2.0.0"), if tracked.
 */
existing_version: string | null, };
