// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionSource } from "./CollectionSource";
import type { PinnedVersionRole } from "./PinnedVersionRole";

/**
 * A pinned spec version associated with a collection.
 *
 * Pinned versions allow users and AI to compare staged specs against the
 * active spec before committing to a version swap.
 */
export type PinnedSpecVersion = { 
/**
 * Unique identifier for this pinned version.
 */
id: string, 
/**
 * Human-readable label (defaults to `info.version` from spec).
 */
label: string, 
/**
 * Raw YAML/JSON spec content.
 */
spec_content: string, 
/**
 * Source the spec was fetched from.
 */
source: CollectionSource, 
/**
 * RFC 3339 UTC timestamp when this version was pinned.
 */
imported_at: string, 
/**
 * Role of this pinned version.
 */
role: PinnedVersionRole, };
