// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent project context representing the user's current working state.
 *
 * This is the single source of truth for "what is the user working on?"
 * and is readable/writable by both the UI and MCP tools.
 */
export type ProjectContext = { 
/**
 * The collection the user is currently working in.
 */
activeCollectionId: string | null, 
/**
 * The request the user is currently focused on.
 */
activeRequestId: string | null, 
/**
 * Free-text notes from the user or AI about the current investigation.
 */
investigationNotes: string | null, 
/**
 * The last N executed request IDs (most recent first, max 10).
 */
recentRequestIds: Array<string>, 
/**
 * User or AI labels for the current session.
 */
tags: Array<string>, };
