// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this collection was created.
 *
 * Import order matters for competitive positioning:
 * - openapi: Primary differentiation (spec-bound requests)
 * - postman: Largest user base to capture
 * - bruno: Growing open-source competitor
 * - insomnia: Users fleeing Kong's forced-login
 * - curl: Import from cURL commands
 * - manual: User created from scratch
 */
export type SourceType = "openapi" | "postman" | "bruno" | "insomnia" | "curl" | "manual";
