// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The lifecycle status of a suggestion.
 */
export type SuggestionStatus = "pending" | "accepted" | "dismissed";
