// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of an available template.
 */
export type TemplateSummary = { 
/**
 * Unique template identifier.
 */
id: string, 
/**
 * Human-readable template name.
 */
name: string, 
/**
 * Template type (`OpenAPI`, workflow, etc).
 */
templateType: string, };
