name: 'Setup Node.js Environment'
description: 'Composite action to set up Node.js environment with just, Motion+ token, and dependencies'
inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  install-just:
    description: 'Whether to install just'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install just
      if: ${{ inputs.install-just == 'true' }}
      uses: extractions/setup-just@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: just install
